version: "3"
services: 
  backend: 
    build: 
      context: .
      args: 
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DEV_DB_ROOT_USER=root
      - DEV_DB_USERNAME=user
      - DEV_DB_PASSWORD=password
      - DEV_DB_ROOT_PASSWORD=password
      - DEV_DB_DATABASE=studyweb_db
      - DEV_DB_HOST=mysql
      - SECRET_JWT=secretjwt
      - SECRET_EMAIL=secretemail
    depends_on:
      - mysql
    command: npm run dev
    ports: 
      - "3000:3000"
  mysql: 
    image: mysql:5.7.24
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studyweb_db
    volumes:
      - mysql-volume:/var/lib/mysql
volumes: 
  mysql-volume: